services:
  ml-flow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-flow
    restart: always
    init: true
    volumes:
      - ./app:/app
      - ./data:/data
      - ./cache-modelscope:/root/.cache/modelscope
      - /etc/localtime:/etc/localtime:ro
    tty: true
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  sing-box:
    build:
      context: ./sing-box
      dockerfile: Dockerfile
    container_name: sing-box-clash
    env_file:
      - ./.env
    ports:
      - "7890:7890" # HTTP proxy
    restart: unless-stopped
