services:
  ml-flow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-flow
    restart: always
    init: true
    volumes:
      - ./app:/app
      - ./data:/data
      - ./cache-modelscope:/root/.cache/modelscope
      - /etc/localtime:/etc/localtime:ro
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

