services:
  clash-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clash-client
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - SUBSCRIPTION_URL=https://connect.applecross.link/clash/702400/Qm7pnGtLKLQX
      - UPDATE_INTERVAL=86400
    ports:
      - "7890:7890" # HTTP 代理
      - "7891:7891" # SOCKS5 代理
      - "9090:9090" # Clash 仪表盘
